// Generated by gencpp from file tests/CECommandResult.msg
// DO NOT EDIT!


#ifndef TESTS_MESSAGE_CECOMMANDRESULT_H
#define TESTS_MESSAGE_CECOMMANDRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tests
{
template <class ContainerAllocator>
struct CECommandResult_
{
  typedef CECommandResult_<ContainerAllocator> Type;

  CECommandResult_()
    : returnCode(0)  {
    }
  CECommandResult_(const ContainerAllocator& _alloc)
    : returnCode(0)  {
    }



   typedef uint32_t _returnCode_type;
  _returnCode_type returnCode;




  typedef boost::shared_ptr< ::tests::CECommandResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tests::CECommandResult_<ContainerAllocator> const> ConstPtr;

}; // struct CECommandResult_

typedef ::tests::CECommandResult_<std::allocator<void> > CECommandResult;

typedef boost::shared_ptr< ::tests::CECommandResult > CECommandResultPtr;
typedef boost::shared_ptr< ::tests::CECommandResult const> CECommandResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tests::CECommandResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tests::CECommandResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tests

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'tests': ['/home/gbrill/ws2/src/tests/msg', '/home/gbrill/ws2/devel/share/tests/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tests::CECommandResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tests::CECommandResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tests::CECommandResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tests::CECommandResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tests::CECommandResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tests::CECommandResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tests::CECommandResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e97ab3f4720d65314a83949dfea8991";
  }

  static const char* value(const ::tests::CECommandResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e97ab3f4720d653ULL;
  static const uint64_t static_value2 = 0x14a83949dfea8991ULL;
};

template<class ContainerAllocator>
struct DataType< ::tests::CECommandResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tests/CECommandResult";
  }

  static const char* value(const ::tests::CECommandResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tests::CECommandResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
uint32 returnCode\n\
";
  }

  static const char* value(const ::tests::CECommandResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tests::CECommandResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.returnCode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CECommandResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tests::CECommandResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tests::CECommandResult_<ContainerAllocator>& v)
  {
    s << indent << "returnCode: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.returnCode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESTS_MESSAGE_CECOMMANDRESULT_H
