// Generated by gencpp from file triangulator/beaconSettings.msg
// DO NOT EDIT!


#ifndef TRIANGULATOR_MESSAGE_BEACONSETTINGS_H
#define TRIANGULATOR_MESSAGE_BEACONSETTINGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <triangulator/beaconSetting.h>

namespace triangulator
{
template <class ContainerAllocator>
struct beaconSettings_
{
  typedef beaconSettings_<ContainerAllocator> Type;

  beaconSettings_()
    : beaconValues()  {
    }
  beaconSettings_(const ContainerAllocator& _alloc)
    : beaconValues(_alloc)  {
    }



   typedef std::vector< ::triangulator::beaconSetting_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::triangulator::beaconSetting_<ContainerAllocator> >::other >  _beaconValues_type;
  _beaconValues_type beaconValues;




  typedef boost::shared_ptr< ::triangulator::beaconSettings_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::triangulator::beaconSettings_<ContainerAllocator> const> ConstPtr;

}; // struct beaconSettings_

typedef ::triangulator::beaconSettings_<std::allocator<void> > beaconSettings;

typedef boost::shared_ptr< ::triangulator::beaconSettings > beaconSettingsPtr;
typedef boost::shared_ptr< ::triangulator::beaconSettings const> beaconSettingsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::triangulator::beaconSettings_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::triangulator::beaconSettings_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace triangulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'triangulator': ['/home/gbrill/catkin_ws/src/triangulator_service/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::triangulator::beaconSettings_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::triangulator::beaconSettings_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::triangulator::beaconSettings_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::triangulator::beaconSettings_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::triangulator::beaconSettings_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::triangulator::beaconSettings_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::triangulator::beaconSettings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0356089f67b16e38dbcecf75c6dce3ef";
  }

  static const char* value(const ::triangulator::beaconSettings_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0356089f67b16e38ULL;
  static const uint64_t static_value2 = 0xdbcecf75c6dce3efULL;
};

template<class ContainerAllocator>
struct DataType< ::triangulator::beaconSettings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "triangulator/beaconSettings";
  }

  static const char* value(const ::triangulator::beaconSettings_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::triangulator::beaconSettings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beaconSetting[] beaconValues\n\
\n\
================================================================================\n\
MSG: triangulator/beaconSetting\n\
float32 beaconID\n\
string beaconName\n\
float32 X\n\
float32 Y\n\
float32 Z\n\
";
  }

  static const char* value(const ::triangulator::beaconSettings_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::triangulator::beaconSettings_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.beaconValues);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct beaconSettings_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::triangulator::beaconSettings_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::triangulator::beaconSettings_<ContainerAllocator>& v)
  {
    s << indent << "beaconValues[]" << std::endl;
    for (size_t i = 0; i < v.beaconValues.size(); ++i)
    {
      s << indent << "  beaconValues[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::triangulator::beaconSetting_<ContainerAllocator> >::stream(s, indent + "    ", v.beaconValues[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRIANGULATOR_MESSAGE_BEACONSETTINGS_H
