// Generated by gencpp from file triangulator/beaconSetting.msg
// DO NOT EDIT!


#ifndef TRIANGULATOR_MESSAGE_BEACONSETTING_H
#define TRIANGULATOR_MESSAGE_BEACONSETTING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace triangulator
{
template <class ContainerAllocator>
struct beaconSetting_
{
  typedef beaconSetting_<ContainerAllocator> Type;

  beaconSetting_()
    : beaconID(0.0)
    , beaconName()
    , X(0.0)
    , Y(0.0)
    , Z(0.0)  {
    }
  beaconSetting_(const ContainerAllocator& _alloc)
    : beaconID(0.0)
    , beaconName(_alloc)
    , X(0.0)
    , Y(0.0)
    , Z(0.0)  {
    }



   typedef float _beaconID_type;
  _beaconID_type beaconID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _beaconName_type;
  _beaconName_type beaconName;

   typedef float _X_type;
  _X_type X;

   typedef float _Y_type;
  _Y_type Y;

   typedef float _Z_type;
  _Z_type Z;




  typedef boost::shared_ptr< ::triangulator::beaconSetting_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::triangulator::beaconSetting_<ContainerAllocator> const> ConstPtr;

}; // struct beaconSetting_

typedef ::triangulator::beaconSetting_<std::allocator<void> > beaconSetting;

typedef boost::shared_ptr< ::triangulator::beaconSetting > beaconSettingPtr;
typedef boost::shared_ptr< ::triangulator::beaconSetting const> beaconSettingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::triangulator::beaconSetting_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::triangulator::beaconSetting_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace triangulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'triangulator': ['/home/gbrill/catkin_ws/src/triangulator_service/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::triangulator::beaconSetting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::triangulator::beaconSetting_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::triangulator::beaconSetting_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::triangulator::beaconSetting_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::triangulator::beaconSetting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::triangulator::beaconSetting_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::triangulator::beaconSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8ab05709826cec7ebcec454552a9cdd";
  }

  static const char* value(const ::triangulator::beaconSetting_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8ab05709826cec7ULL;
  static const uint64_t static_value2 = 0xebcec454552a9cddULL;
};

template<class ContainerAllocator>
struct DataType< ::triangulator::beaconSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "triangulator/beaconSetting";
  }

  static const char* value(const ::triangulator::beaconSetting_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::triangulator::beaconSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 beaconID\n\
string beaconName\n\
float32 X\n\
float32 Y\n\
float32 Z\n\
";
  }

  static const char* value(const ::triangulator::beaconSetting_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::triangulator::beaconSetting_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.beaconID);
      stream.next(m.beaconName);
      stream.next(m.X);
      stream.next(m.Y);
      stream.next(m.Z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct beaconSetting_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::triangulator::beaconSetting_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::triangulator::beaconSetting_<ContainerAllocator>& v)
  {
    s << indent << "beaconID: ";
    Printer<float>::stream(s, indent + "  ", v.beaconID);
    s << indent << "beaconName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.beaconName);
    s << indent << "X: ";
    Printer<float>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<float>::stream(s, indent + "  ", v.Y);
    s << indent << "Z: ";
    Printer<float>::stream(s, indent + "  ", v.Z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRIANGULATOR_MESSAGE_BEACONSETTING_H
