// Generated by gencpp from file triangulator/triangulatorResponse.msg
// DO NOT EDIT!


#ifndef TRIANGULATOR_MESSAGE_TRIANGULATORRESPONSE_H
#define TRIANGULATOR_MESSAGE_TRIANGULATORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace triangulator
{
template <class ContainerAllocator>
struct triangulatorResponse_
{
  typedef triangulatorResponse_<ContainerAllocator> Type;

  triangulatorResponse_()
    : returnCode(0)  {
    }
  triangulatorResponse_(const ContainerAllocator& _alloc)
    : returnCode(0)  {
    }



   typedef uint32_t _returnCode_type;
  _returnCode_type returnCode;




  typedef boost::shared_ptr< ::triangulator::triangulatorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::triangulator::triangulatorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct triangulatorResponse_

typedef ::triangulator::triangulatorResponse_<std::allocator<void> > triangulatorResponse;

typedef boost::shared_ptr< ::triangulator::triangulatorResponse > triangulatorResponsePtr;
typedef boost::shared_ptr< ::triangulator::triangulatorResponse const> triangulatorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::triangulator::triangulatorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::triangulator::triangulatorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace triangulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'triangulator': ['/home/gbrill/catkin_ws/src/triangulator_service/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::triangulator::triangulatorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::triangulator::triangulatorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::triangulator::triangulatorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::triangulator::triangulatorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::triangulator::triangulatorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::triangulator::triangulatorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::triangulator::triangulatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e97ab3f4720d65314a83949dfea8991";
  }

  static const char* value(const ::triangulator::triangulatorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e97ab3f4720d653ULL;
  static const uint64_t static_value2 = 0x14a83949dfea8991ULL;
};

template<class ContainerAllocator>
struct DataType< ::triangulator::triangulatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "triangulator/triangulatorResponse";
  }

  static const char* value(const ::triangulator::triangulatorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::triangulator::triangulatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 returnCode\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::triangulator::triangulatorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::triangulator::triangulatorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.returnCode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct triangulatorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::triangulator::triangulatorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::triangulator::triangulatorResponse_<ContainerAllocator>& v)
  {
    s << indent << "returnCode: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.returnCode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRIANGULATOR_MESSAGE_TRIANGULATORRESPONSE_H
